### ISSUE TITLE
Code and dateset release

### ISSUE THREAD

**Issue by SomaNonaka** [ChenyanWu/MEBOW#1]
Hi, 

I found your paper really interesting and would like to try your methods. 
Could you please tell me your plan to publish the codes and dataset?

**Comment by ChenyanWu** [comment]
Thank you for your interest! 
The dataset belongs to Amazon. I am still waiting for their approval to release dataset. That should be about two weeks. I have already prepared the dataset and code. As long as Amazon side approves, I will make the dataset and code public.

**Comment by SomaNonaka** [comment]
Thank you for your reply! I'm looking forward to it.
