### ISSUE TITLE
TUD dataset

### ISSUE THREAD

**Issue by HHH-AOAO** [ChenyanWu/MEBOW#2]
Hi,thanks for your excellent work! I'm doing some research on pedestrain orientation recognition，and I may use the TUD dataset which has been relabeled with continuous orientation labels, however I don't find a way to obtain it .

Looking forward to your reply！thanks

**Comment by ChenyanWu** [comment]
I have already put some useful links for TUD dataset on README.md.

**Comment by HHH-AOAO** [comment]
Thanks for your reply
