### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset.fusion'

### ISSUE THREAD

**Issue by DRSY** [ChenyanWu/MEBOW#5]
I am running experiments on the MEBOW dataset but encountered this error. I checked and found that there is indeed no such module named fusion in the lib/dataset folder.

Any idea how to fix this?

**Comment by ChenyanWu** [comment]
Datasets fusion is not needed in this code. You can just remove the code "import dataset.fusion". By the way, where is "dataset.fusion" in this repo.

**Comment by DRSY** [comment]
> Datasets fusion is not needed in this code. You can just remove the code "import dataset.fusion". By the way, where is "dataset.fusion" in this repo.

in lib/dataset/__init__.py, there is one line of such code. I have removed it and now it works.
Thanks!

**Comment by piercus** [comment]
@ChenyanWu thank you for this work

I have opened #6 for this,

**Comment by ChenyanWu** [comment]
Thanks!

**Comment by ChenyanWu** [comment]
> @ChenyanWu thank you for this work
> 
> I have opened #6 for this,

Thanks
